prometheus_url = "http://prometheus_url"
region_id = "region_id"
usage_data_dir = "/tmp/usage"
bucket_usage_data_dir = "/tmp/usage_bucket"
log_path = "/var/log/yig/billing.log"

enable_post_billing_cron = true
post_billing_spec = "@hourly"
spark_home = "/home/tidb/data/deploy/spark"
tispark_shell = "/etc/yig/fetch_usage.sh"
tispark_shell_bucket = "/etc/yig/fetch_usage_bucket.sh"

enable_usage_cache = true
redis_url = "10.5.0.8:6379"
redis_password = "hehehehe"

kafka_server = "kafka:29092"
kafka_group_id = "myGroup"
kafka_topic = "testTopic2"

[producer]
url="url"
path = "path"
accessKey = "accessKey"
secretKey = "secretAccessKey"
